---
Name: checkfront-module-routes
# internal routes directly to checkfront controllers not pages.
---
Director:
  rules:
    'package/book': CheckfrontPackageController
    'package/link-generator': CheckfrontLinkGeneratorController
    'checkfront/link-generator': CheckfrontLinkGeneratorController
