---
Name: checkfront-module-routes
# internal routes directly to checkfront controllers not pages.
---
Director:
  rules:
    'package/link-generator': CheckfrontLinkGeneratorController       # route to link generator
