---
Name: checkfront-module-routes
---
Director:
  rules:
    'checkfront/item': CheckfrontItemController
    'checkfront/package': CheckfrontPackageController
    'checkfront/link-generator': CheckfrontLinkGeneratorController
