---
Name: checkfront-module-routes
# internal routes directly to checkfront controllers not pages.
---
Director:
  rules:
    'checkfront/package/book': CheckfrontPackageController                       # route to private booking page
    'checkfront/package/link-generator': CheckfrontLinkGeneratorController       # route to link generator
